run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - varnamelen
    - forbidigo
    - goimports
    - exportloopref

  fast: false

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/hahapathetic/task-7)
    skip-generated: false
    custom-order: true
  depguard:
    rules:
      main:
        files:
          - !$test
        allow:
          - $gostd
          - github.com/mdlayher/wifi
#output:
#  formats:
#    - format: checkstyle
#      path: ../golang_ci/ci_report.xml