CREATE TABLE IF NOT EXISTS contacts(
    ID    SERIAL PRIMARY KEY,
    Name  VARCHAR(255) NOT NULL,
    Phone VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP NOT NULL
);