// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package wifi_test

import (
	mock "github.com/stretchr/testify/mock"

	wifi "github.com/mdlayher/wifi"
)

// WiFi is an autogenerated mock type for the WiFi type
type WiFi struct {
	mock.Mock
}

// Interfaces provides a mock function with given fields:
func (_m *WiFi) Interfaces() ([]*wifi.Interface, error) {
	ret := _m.Called()

	var r0 []*wifi.Interface
	if rf, ok := ret.Get(0).(func() []*wifi.Interface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*wifi.Interface)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWiFi interface {
	mock.TestingT
	Cleanup(func())
}

// NewWiFi creates a new instance of WiFi. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWiFi(t mockConstructorTestingTNewWiFi) *WiFi {
	mock := &WiFi{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
