// Code generated by mockery v2.49.1. DO NOT EDIT.

package mock_test

import mock "github.com/stretchr/testify/mock"

// Doer is an autogenerated mock type for the Doer type
type Doer struct {
	mock.Mock
}

// DoSomething provides a mock function with given fields: _a0, _a1
func (_m *Doer) DoSomething(_a0 int, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DoSomething")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDoer creates a new instance of Doer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Doer {
	mock := &Doer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
