name: udalov_alex

on:
  push:
    branches: [ "TASK-7" ]

jobs:
  task-7:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test db
      working-directory: ./alex.udalov/task-7
      run: go test -v ./internal/db/...

    - name: Test WiFi
      working-directory: ./alex.udalov/task-7
      run: go test -v ./internal/wifi/...