name: danil_novokhatskiy
on:
  push:
    branches: ["danil.novokhatskiy/task-7"]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configuration of Golang
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'
      - name: Test DataBase
        run: go test ./internal/db
        working-directory: danil.novokhatskiy/task-7

      - name: Test Wifi
        run: go test ./internal/wifi
        working-directory: danil.novokhatskiy/task-7


  golangci:
    name: linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.0
          working-directory: danil.novokhatskiy/task-7

