name: Go Tests and Lint

on:
  push:
    branches: ["matvey.shmonov/task-7"]
  pull_request:
    branches: ["matvey.shmonov/task-7"]

jobs:
  lint:
    name: Run GolangCI-Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Install golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint
        working-directory: ./matvey.shmonov/task-7
        run: |
          golangci-lint run ./...

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1' # Укажите нужную версию Go

      - name: Run Tests
        working-directory: ./matvey.shmonov/task-7
        run: |
          go test ./... -v -cover