name: sofia_dudkina
on:
  push:
    branches: [ "sofia.dudkina/task-7" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
      - name: Test db
        run: go test ./internal/db
        working-directory: sofia.dudkina/task-7
      - name: Test WiFi
        run: go test ./internal/wifi
        working-directory: sofia.dudkina/task-7
      - name: Install golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.0
      - name: Linting internal
        run: golangci-lint run
        working-directory: sofia.dudkina/task-7/internal
      - name: Linting cmd
        run: golangci-lint run
        working-directory: sofia.dudkina/task-7/cmd